a = input('digite algo:  ')
print('O tipo primitivo é ?', type(a))
print('so tem espaco ?', a.isspace())
print('e um numero ?', a.isnumeric())
print(' e alfabetico ?', a.isalpha())
print(' e alfanumerico ?', a.isalnum())
print(' esta em maiusculo ?', a.isupper())
print(' esta em minusculo ?', a.islower())
print(' esta capitalizada ?',a.istitle())